import Head from 'next/head';
import React from 'react';
import Navbar from '../../components/navbar';
import BlogPage from '../../layouts/blog';
import styles from '../../styles/Home.module.css';

const Blog: React.FC = () => (
  <div className={styles.container}>
    <Head>
      <title>Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/css/uikit.min.css"
      />
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.min.js"
        async
      />
      <script
        src="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/js/uikit-icons.min.js"
        async
      />
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.js"
        async
      />
    </Head>
    <main>
      <Navbar />
      <BlogPage />
    </main>
  </div>
);

export default Blog;
