import { FooterComponent } from 'components/footer';
import { AuthorContent } from 'features/site/author-content';
import { AuthorHeader } from 'features/site/author-header';
import { LastPosts } from 'features/site/last-posts';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Layout } from '../layouts/content';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
      <AuthorHeader />
      <AuthorContent />
      <LastPosts />
      <FooterComponent />
    </Layout>
  </div>
);

export default Home;
