import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Articles } from "../components/articles";
import Navbar from "../components/navbar";
import HomePage from "../layouts/homepage";
import styles from "../styles/Home.module.css";

export interface ListProps {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

const Home: NextPage = () => {
  const [state, setState] = useState<ListProps[]>([] as unknown as ListProps[]);

  useEffect(() => {
    (async () => {
      const res = await fetch("https://jsonplaceholder.typicode.com/todos");
      const data = await res.json();
      setState(data);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/css/uikit.min.css"
        />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.min.js" async></script>
        <script src="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/js/uikit-icons.min.js" async></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.js" async></script>
      </Head>

      <main>
        <Navbar />
        <HomePage />
      </main>
    </div>
  );
};

export default Home;
